apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: {{ .Values.issuer.name }}
 namespace: {{ .Values.namespace }}
spec:
 acme:
   email: {{ .Values.issuer.email }}
   # We use the staging server here for testing to avoid hitting
   server: {{ .Values.issuer.server.prod }}
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: {{ .Values.issuer.privateKeySecretRef.name }}
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik